# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Dae Hyun Lee
email: dhlee4 at uw.edu
description: > # this means to ignore newlines until "baseurl:"
  My name is Dae Hyun Lee and I'm Ph.D. student studing for biomedical and health informatics from University of Washington. I'm big enthusiest for applying interpretable machine learning approaches to clinical data to predict future adverse event or discover novel care pathway which allow us to improve current practice.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://dhlee4.github.io" # the base hostname & protocol for your site
github_username:  dhlee4

# Build settings
markdown: kramdown
